language: node_js
sudo: false
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - git clone https://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - export PATH=$PATH:`pwd`/bin
  - cd -
before_script:
  - phantomjs --version
  - casperjs --version
